steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Run linting
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'lint']
    id: 'lint'

  # Build TypeScript
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build'

  # Deploy the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'customerSummary'
      - '--gen2'
      - '--runtime=nodejs18'
      - '--region=us-central1'
      - '--source=.'
      - '--entry-point=customerSummary'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT=${PROJECT_ID}'
      - '--set-secrets=BQ_TABLE_REF=BQ_TABLE_REF:latest'
    secretEnv: ['BQ_TABLE_REF']
    id: 'deploy'

timeout: '1800s'  # 30 minutes
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1  # Default region, can be overridden in trigger

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/BQ_TABLE_REF/versions/latest
      env: 'BQ_TABLE_REF'
